apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80