replicaCount: 3

image:
  repository: myregistry/myapp
  tag: latest

ingress:
  enabled: true
  hostname: myapp.domain.com

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 50

mysql:
  auth:
    password: "your_root_password"

phpmyadmin:
  php:
    env:
      PMA_PASSWORD: "your_root_password"

prometheus:
  prometheus:
  scrapeInterval: 15s
  evaluationInterval: 15s

grafana:
  adminUser: admin
  adminPassword: "secureP@ssw0rd123!"
  dashboards:
    default:
      kubernetes-pods:
        json: |
          {
            "annotations": {
              "list": []
            },
            "editable": true,
            "panels": [
              {
                "title": "Pod Status",
                "type": "gauge",
                "datasource": "Prometheus",
                "targets": [
                  {
                    "expr": "sum(kube_pod_status_phase{phase=\"Running\"}) / sum(kube_pod_status_phase) * 100",
                    "legendFormat": "Running Pods %"
                  }
                ]
              },
              {
                "title": "Pod CPU Usage",
                "type": "graph",
                "datasource": "Prometheus",
                "targets": [
                  {
                    "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) by (pod)",
                    "legendFormat": "{{pod}}"
                  }
                ]
              },
              {
                "title": "Pod Memory Usage",
                "type": "graph",
                "datasource": "Prometheus",
                "targets": [
                  {
                    "expr": "sum(container_memory_usage_bytes{container!=\"\"}) by (pod)",
                    "legendFormat": "{{pod}}"
                  }
                ]
              }
            ],
            "refresh": "10s",
            "schemaVersion": 33,
            "title": "Kubernetes Pods Overview",
            "version": 1
          }
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server
          access: proxy
          isDefault: true

persistence:
  enabled: true
  size: 10Gi

service:
  type: LoadBalancer
